In [2]:
import requests 
import numpy as np
import pandas as pd
import pprint
from bs4 import BeautifulSoup

In [3]:
headers = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    "Accept-Language": "en-US,en;q=0.9"
}

In [4]:
male_url = "https://murderpedia.org/male.A/index.A.htm"
female_url = "https://murderpedia.org/female.A/index.A.htm"
male_response = requests.get(male_url, headers=headers)
female_response = requests.get(female_url, headers=headers)

male_soup = BeautifulSoup(male_response.text, "html.parser")
female_soup = BeautifulSoup(female_response.text, "html.parser")

In [5]:
male_response

In [6]:
female_response

In [26]:
#Since both are 200 they are good to use!
#First thing I want to do is get all of their names and then I will match their crime and gender to it and etc.

In [7]:
#Finding all male names
names = []
tags = male_soup.find_all('a', href=True)

for link in tags:
    href = link.get('href')
    x = link.get_text(" ", strip=True)
#Killer profile ends with .htm
    if href.endswith('.htm'):
        if 'index' not in href:
                names.append(x)

print(names)

['Abbas\n                Baqir', 'ABBAS', 'Burton W. ABBOTT', 'Jack Henry ABBOTT', 'William Keith ABBOTT', 'Azad ABDULLAH', 'Herisch Ali ABDULLAH', 'Ricky ABEYTA', 'Roderick ABEYTA', 'Nathaniel \n\t\t\tJamal ABRAHAM', 'Myer ABRAMOVICH', 'Elias', 'ABUELAZAM', 'Saber & Mahmoud ABU-EL-ULLA', 'Mumia ABU-JAMAL', 'Ali \n              Hassan ABU JAMAL', 'Elias ACEVEDO Sr.', 'Francisco ACEVEDO', 'Daniel Clate ACKER', 'Lorne\n                Joe ACQUIN', 'Robert James ACREMANT', 'Aubrey Dennis ADAMS Jr.', 'Bennie ADAMS', 'Beunka ADAMS', 'Edward J. ADAMS', 'James ADAMS', 'John \n\t\t\t\tWade ADAMS', 'Dr.\n                John Bodkin ADAMS', 'Richard Lee ADAMS', 'Sylvester Lewis ADAMS', 'Timothy Wayne ADAMS', 'William Nelson ADAMS', 'Dwight \n\t\t\t\tDwayne ADANANDUS', 'Kazeem ADEYEMO', 'Jim David ADKISSON', 'George \n                C. ADORNO', 'David AFUTA', 'Joseph Moreno AGUAYO', 'Jesus \n\t\t\tLedesma AGUILAR', 'Tonatihu AGUILAR', 'Jesus AGUILERA', 'Nazir AHMAD', 'Shahidul AHMED', 'H asan AKBAR', 'Glen \n\t\t\tBurton AKE', 'Thomas Wayne AKERS', 'Joseph Dewey', 'AKIN', 'Stephen AKINMURELE', 'John Avalos ALBA', 'Charles ALBANESE', 'Gameel AL-BATOUTI', 'Charles Frederick ALBRIGHT', 'Rodney James ALCALA', 'John James ALCOTT', 'Jack Edward ALDERMAN', 'Donald Loren ALDRICH', 'Patrice ALÈGRE', 'Andre ALEXANDER', 'Caruthers ALEXANDER', 'Aaron ALEXIS', 'Arif and Farman ALI', 'Michael ALIG', 'Franklin \n\t\t\t\tDeWayne ALIX', 'Jean-Pierre ALLAIN', 'Edward\n                Charles ALLAWAY', 'Thomas Henry ALLAWAY', 'Clarence Ray ALLEN', 'Dyson ALLEN', 'Floyd ALLEN', 'Garry Thomas ALLEN', 'Guy ALLEN', 'Howard Arthur ALLEN', 'John\n                Edward ALLEN', 'Kerry Dimart ALLEN', 'Lloyd Chase ALLEN', 'Peter Anthony ALLEN', 'Quincy Javon ALLEN', 'Stanley Edward ALLEN', 'Sedley ALLEY', 'Curtis \n              Michael ALLGIER', 'Shareef ALLMAN', 'James Vernon ALLRIDGE III', 'Ronald \n\t\t\tKeith ALLRIDGE', 'Sahib Lateef AL-MOSAWI', 'Yahya Hussein AL-RAGHWAH', 'Charlie Mason ALSTON Jr.', 'P ressley \n\t\t\t\tBernard ALSTON', 'Lorenzo ALVARADO', 'Steven Brian ALVARADO', 'Juan Carlos ÁLVAREZ', 'Juan \n                Manuel ÁLVAREZ', 'Manuel Machado ÁLVAREZ', 'Billy Don ALVERSON', 'Gary \n\t\t\t\tEldon ALVORD', 'J ohn \n\t\t\t\tJoe AMADOR', 'Abdelali AMER', 'Triston Jay AMERO', 'Yigal AMIR', 'Bernard Eugene AMOS', 'Lowell \n\t\t\t\tEdwin AMOS', 'Nordine AMRANI', 'Joseph D. AMRINE', 'Ambrosio ANALCO RAMIREZ', 'Johan Alfred Andersson ANDER', 'Roger ANDERMATT', 'Allen Leroy ANDERSON', 'Anthony ANDERSON', 'Chad \n              Jason ANDERSON', 'Charles L. ANDERSON', 'Curtis Dean ANDERSON', 'Dale\n                R. ANDERSON', 'David ANDERSON', 'Frank Winfield ANDERSON', 'Fred ANDERSON Jr.', 'Jesse ANDERSON', 'Johnny Ray ANDERSON', 'Larry \n\t\t\t\tNorman ANDERSON', 'Michael John ANDERSON', 'Newton Burton ANDERSON', 'Percy Charles ANDERSON', 'Richard\n                Harold ANDERSON', 'Robert \n\t\t\tJames ANDERSON', 'Robert Leroy ANDERSON', 'Stephen \n\t\t\t\tLawrence ANDERSON', 'Stephen Wayne ANDERSON', 'Terrance L. ANDERSON', 'Richard ANDRADE', 'Rogelio ANDRADE', 'James Douglas ANDREWS', 'Joshua Wayne ANDREWS', 'Larry Donnell ANDREWS', 'Lowell \n              Lee ANDREWS', 'Ralph \n\t\t\t\tRaymond ANDREWS', 'William ANDREWS', 'Terence ANDRUS', 'Richard ANGELO', 'Fritz Heinrich ANGERSTEIN', 'R oger \n\t\t\t\tNicholas ANGLETON', 'Klaas ANNINK', 'Artem ANOUFRIEV', 'D avid \n\t\t\t\tLamar ANTHONY', 'Abram ANTONE', 'Anthony ANTONE', 'Mauro ANTONELLO', 'Narding ANZURES', 'Michael APELT', 'Rudi APELT', 'Siavosh\n              Rahmani AQDAM', 'Eugene ARAM', 'Arturo Daniel ARANDA', 'Guillermo Octavio ARBELAEZ', 'Roscoe \n\t\t\t\tConkling ARBUCKLE', 'Francisco ARCE MONTES', 'Jonathan ARCE', 'James ARCENE', 'Robin Lee ARCHER', 'William\n                Dale ARCHERD', 'T hayne \n\t\t\t\tH. ARCHIBALD', 'Gilbert \n              Eugenio ARCHIBEQUE', 'Gregorio ARELLANO', 'Jeffrey ARENBURG', 'Roberto ARGÜELLES', 'Gumaro de Dios ARIAS', 'Pedro ARIAS', 'David ARISMAN', 'Jackie ARKLÖV', 'Anthony Paul ARKWRIGHT', 'Charles W. ARMENTROUT III', 'Herbert Rowse ARMSTRONG', 'John\n                Eric ARMSTRONG', 'Lancelot ARMSTRONG', 'Pleasant ARMSTRONG', 'Ralph Dale ARMSTRONG', 'Shad Daniel ARMSTRONG', 'Shaun Anthony ARMSTRONG', 'Jermarr Carlos ARNOLD', 'John\n                D. ARNOLD', 'Levi ARON', 'R andy ARROYO BAEZ', 'Rahan ARSHAD', 'M ark \n\t\t\t\tSam ARTHUR', 'Tommy ARTHUR', 'Dante Wyndham ARTHURS', 'Kevin Lloyd ARTZ', 'Shoko ASAHARA', 'Kojiro ASAKURA', 'Mark James ASAY', 'Larry\n                Gene ASHBROOK', 'Lazale \n              Delane ASHBY', 'Troy Adam ASHMUS', 'Herman Dale ASHWORTH', 'Valery ASRATYAN', 'Andrew Simon ASTON', 'Samuel ATHERLEY', 'Benjamin Tony ATKINS', 'Daryl Renard ATKINS', 'Frederick Benjamin ATKINS', 'Joseph Ernest ATKINS', 'Philliph \n\t\t\t\tAlexander ATKINS', 'David Edward ATTIAS', 'Jeffrey \n\t\t\tLee ATWATER', 'Frank Jarvis ATWOOD', 'Robert Ronald ATWORTH', 'J ohn AUSONIUS', 'Ernest AUSTIN', 'Perry Allen AUSTIN', 'James David AUTRY', 'Pekka-Eric AUVINEN', 'Jorjik AVANESIAN', 'Rufus Lee AVERHART', 'Steven AVERY', 'Alejandro AVILA', 'Gabriel \n              Adrian AVILA', 'Rigoberto AVILA Jr.', 'Dr.\n                Arnold Asher AXILROD', 'Erik Salvador AYALA', 'C arlos \n\t\t\t\tManuel AYESTAS', 'Anthony AYRES', 'Johnson AZIGA', 'last \n          updates']

In [8]:
#Need to clean it up..
clean_names = []
male_links = []
for n in names:
    if n != None: #Making sure the name is not empty
        n = n.replace("\n", " ") #fixing the /
        n = n.replace("\t", " ")  #fixing so it has normal spacing 
        n = " ".join(n.split())   #https://www.geeksforgeeks.org/python/python-removing-newline-character-from-string/ 
        if n.lower() != "last updates": #Removing this from the end
                clean_names.append(n)

print(clean_names)
print(len(clean_names))

['Abbas Baqir', 'ABBAS', 'Burton W. ABBOTT', 'Jack Henry ABBOTT', 'William Keith ABBOTT', 'Azad ABDULLAH', 'Herisch Ali ABDULLAH', 'Ricky ABEYTA', 'Roderick ABEYTA', 'Nathaniel Jamal ABRAHAM', 'Myer ABRAMOVICH', 'Elias', 'ABUELAZAM', 'Saber & Mahmoud ABU-EL-ULLA', 'Mumia ABU-JAMAL', 'Ali Hassan ABU JAMAL', 'Elias ACEVEDO Sr.', 'Francisco ACEVEDO', 'Daniel Clate ACKER', 'Lorne Joe ACQUIN', 'Robert James ACREMANT', 'Aubrey Dennis ADAMS Jr.', 'Bennie ADAMS', 'Beunka ADAMS', 'Edward J. ADAMS', 'James ADAMS', 'John Wade ADAMS', 'Dr. John Bodkin ADAMS', 'Richard Lee ADAMS', 'Sylvester Lewis ADAMS', 'Timothy Wayne ADAMS', 'William Nelson ADAMS', 'Dwight Dwayne ADANANDUS', 'Kazeem ADEYEMO', 'Jim David ADKISSON', 'George C. ADORNO', 'David AFUTA', 'Joseph Moreno AGUAYO', 'Jesus Ledesma AGUILAR', 'Tonatihu AGUILAR', 'Jesus AGUILERA', 'Nazir AHMAD', 'Shahidul AHMED', 'H asan AKBAR', 'Glen Burton AKE', 'Thomas Wayne AKERS', 'Joseph Dewey', 'AKIN', 'Stephen AKINMURELE', 'John Avalos ALBA', 'Charles ALBANESE', 'Gameel AL-BATOUTI', 'Charles Frederick ALBRIGHT', 'Rodney James ALCALA', 'John James ALCOTT', 'Jack Edward ALDERMAN', 'Donald Loren ALDRICH', 'Patrice ALÈGRE', 'Andre ALEXANDER', 'Caruthers ALEXANDER', 'Aaron ALEXIS', 'Arif and Farman ALI', 'Michael ALIG', 'Franklin DeWayne ALIX', 'Jean-Pierre ALLAIN', 'Edward Charles ALLAWAY', 'Thomas Henry ALLAWAY', 'Clarence Ray ALLEN', 'Dyson ALLEN', 'Floyd ALLEN', 'Garry Thomas ALLEN', 'Guy ALLEN', 'Howard Arthur ALLEN', 'John Edward ALLEN', 'Kerry Dimart ALLEN', 'Lloyd Chase ALLEN', 'Peter Anthony ALLEN', 'Quincy Javon ALLEN', 'Stanley Edward ALLEN', 'Sedley ALLEY', 'Curtis Michael ALLGIER', 'Shareef ALLMAN', 'James Vernon ALLRIDGE III', 'Ronald Keith ALLRIDGE', 'Sahib Lateef AL-MOSAWI', 'Yahya Hussein AL-RAGHWAH', 'Charlie Mason ALSTON Jr.', 'P ressley Bernard ALSTON', 'Lorenzo ALVARADO', 'Steven Brian ALVARADO', 'Juan Carlos ÁLVAREZ', 'Juan Manuel ÁLVAREZ', 'Manuel Machado ÁLVAREZ', 'Billy Don ALVERSON', 'Gary Eldon ALVORD', 'J ohn Joe AMADOR', 'Abdelali AMER', 'Triston Jay AMERO', 'Yigal AMIR', 'Bernard Eugene AMOS', 'Lowell Edwin AMOS', 'Nordine AMRANI', 'Joseph D. AMRINE', 'Ambrosio ANALCO RAMIREZ', 'Johan Alfred Andersson ANDER', 'Roger ANDERMATT', 'Allen Leroy ANDERSON', 'Anthony ANDERSON', 'Chad Jason ANDERSON', 'Charles L. ANDERSON', 'Curtis Dean ANDERSON', 'Dale R. ANDERSON', 'David ANDERSON', 'Frank Winfield ANDERSON', 'Fred ANDERSON Jr.', 'Jesse ANDERSON', 'Johnny Ray ANDERSON', 'Larry Norman ANDERSON', 'Michael John ANDERSON', 'Newton Burton ANDERSON', 'Percy Charles ANDERSON', 'Richard Harold ANDERSON', 'Robert James ANDERSON', 'Robert Leroy ANDERSON', 'Stephen Lawrence ANDERSON', 'Stephen Wayne ANDERSON', 'Terrance L. ANDERSON', 'Richard ANDRADE', 'Rogelio ANDRADE', 'James Douglas ANDREWS', 'Joshua Wayne ANDREWS', 'Larry Donnell ANDREWS', 'Lowell Lee ANDREWS', 'Ralph Raymond ANDREWS', 'William ANDREWS', 'Terence ANDRUS', 'Richard ANGELO', 'Fritz Heinrich ANGERSTEIN', 'R oger Nicholas ANGLETON', 'Klaas ANNINK', 'Artem ANOUFRIEV', 'D avid Lamar ANTHONY', 'Abram ANTONE', 'Anthony ANTONE', 'Mauro ANTONELLO', 'Narding ANZURES', 'Michael APELT', 'Rudi APELT', 'Siavosh Rahmani AQDAM', 'Eugene ARAM', 'Arturo Daniel ARANDA', 'Guillermo Octavio ARBELAEZ', 'Roscoe Conkling ARBUCKLE', 'Francisco ARCE MONTES', 'Jonathan ARCE', 'James ARCENE', 'Robin Lee ARCHER', 'William Dale ARCHERD', 'T hayne H. ARCHIBALD', 'Gilbert Eugenio ARCHIBEQUE', 'Gregorio ARELLANO', 'Jeffrey ARENBURG', 'Roberto ARGÜELLES', 'Gumaro de Dios ARIAS', 'Pedro ARIAS', 'David ARISMAN', 'Jackie ARKLÖV', 'Anthony Paul ARKWRIGHT', 'Charles W. ARMENTROUT III', 'Herbert Rowse ARMSTRONG', 'John Eric ARMSTRONG', 'Lancelot ARMSTRONG', 'Pleasant ARMSTRONG', 'Ralph Dale ARMSTRONG', 'Shad Daniel ARMSTRONG', 'Shaun Anthony ARMSTRONG', 'Jermarr Carlos ARNOLD', 'John D. ARNOLD', 'Levi ARON', 'R andy ARROYO BAEZ', 'Rahan ARSHAD', 'M ark Sam ARTHUR', 'Tommy ARTHUR', 'Dante Wyndham ARTHURS', 'Kevin Lloyd ARTZ', 'Shoko ASAHARA', 'Kojiro ASAKURA', 'Mark James ASAY', 'Larry Gene ASHBROOK', 'Lazale Delane ASHBY', 'Troy Adam ASHMUS', 'Herman Dale ASHWORTH', 'Valery ASRATYAN', 'Andrew Simon ASTON', 'Samuel ATHERLEY', 'Benjamin Tony ATKINS', 'Daryl Renard ATKINS', 'Frederick Benjamin ATKINS', 'Joseph Ernest ATKINS', 'Philliph Alexander ATKINS', 'David Edward ATTIAS', 'Jeffrey Lee ATWATER', 'Frank Jarvis ATWOOD', 'Robert Ronald ATWORTH', 'J ohn AUSONIUS', 'Ernest AUSTIN', 'Perry Allen AUSTIN', 'James David AUTRY', 'Pekka-Eric AUVINEN', 'Jorjik AVANESIAN', 'Rufus Lee AVERHART', 'Steven AVERY', 'Alejandro AVILA', 'Gabriel Adrian AVILA', 'Rigoberto AVILA Jr.', 'Dr. Arnold Asher AXILROD', 'Erik Salvador AYALA', 'C arlos Manuel AYESTAS', 'Anthony AYRES', 'Johnson AZIGA']
220

In [9]:
#Making the rows for all the males 
male_gender = []

for n in clean_names:
    male_gender.append("Male")
male_df = pd.DataFrame({
    "name": clean_names,
    "gender": male_gender
})

male_df.head(220)

                         name gender
0                 Abbas Baqir   Male
1                       ABBAS   Male
2            Burton W. ABBOTT   Male
3           Jack Henry ABBOTT   Male
4        William Keith ABBOTT   Male
..                        ...    ...
215  Dr. Arnold Asher AXILROD   Male
216       Erik Salvador AYALA   Male
217    C arlos Manuel AYESTAS   Male
218             Anthony AYRES   Male
219             Johnson AZIGA   Male

[220 rows x 2 columns]

In [10]:
#Now doing the same thing for females
female_names = []

tags = female_soup.find_all('a', href=True)

for link in tags:
    href = link.get('href')
    x = link.get_text(" ", strip=True)

    if href.endswith('.htm'):
        if 'index' not in href:
                female_names.append(x)

print(female_names)

['Sada ABE', 'Kristi Anne ABRAHAMS', 'Nicole M. ABUSHARIF', 'Brittny Marie ADAMS', 'Christine ADEWUNMI', 'Kemi ADEYOOLA', 'Lydia ADLER', 'Guen Garlejo AGUILAR', 'Sara María ALDRETE', 'Nasra Yussef Al-ENEZI', 'Maria del Rosio ALFARO', 'Melanie ALIX', 'Patricia \n\n                Taylor ALLANSON', 'Eryn ALLEGRA', 'Margaret ALLEN', 'Margaret Ann ALLEN', 'Shirley Elizabeth ALLEN', 'Wanda Jean ALLEN', 'Beverley Gail ALLITT', 'Angelica Salazar ALVAREZ', 'Teresa ALVAREZ', 'Maria Isabella AMAYA', 'Lyda Catherine AMBROSE', 'Kimberly \n                S. ANDERSON', 'Michele Kristen ANDERSON', 'Brenda Evers ANDREW', 'Jane ANDREWS', 'Julia Rothon ANDREWS', 'Tracie Marguerite ANDREWS', 'Wendi Elizabeth ANDRIANO', 'Catherine ANDRUS', 'Paula ANGEL', 'Mary Ann ANSELL', 'Mary ANTOINE', 'Theresa ANTONINI', 'Anna ANTONIO', 'Amy ARCHER-GILLIGAN', 'Alice ARDEN', 'Jodi Ann ARIAS', 'Nirmala \n                Devi ARJUN', 'LaShanda ARMSTRONG', 'China P. ARNOLD', 'Heather ARNOLD', 'Marie Dean ARRINGTON', 'Gertraud ARZBERGER', 'Gunn-Britt ASHFIELD', 'Lisl AUMAN', 'Zakieya \n                Latrice AVERY', 'Asuncion AVILA-VILLA', 'Shajia AYOBI', 'last \n          updates']

In [31]:
len(female_names)

51

In [11]:
clean_female = []

for n in female_names:
    if n != None:
        n = n.replace("\n", " ")
        n = n.replace("\t", " ")
        n = " ".join(n.split())

        if n.lower() != "last updates":
                clean_female.append(n)

print(clean_female)
print(len(clean_female))

['Sada ABE', 'Kristi Anne ABRAHAMS', 'Nicole M. ABUSHARIF', 'Brittny Marie ADAMS', 'Christine ADEWUNMI', 'Kemi ADEYOOLA', 'Lydia ADLER', 'Guen Garlejo AGUILAR', 'Sara María ALDRETE', 'Nasra Yussef Al-ENEZI', 'Maria del Rosio ALFARO', 'Melanie ALIX', 'Patricia Taylor ALLANSON', 'Eryn ALLEGRA', 'Margaret ALLEN', 'Margaret Ann ALLEN', 'Shirley Elizabeth ALLEN', 'Wanda Jean ALLEN', 'Beverley Gail ALLITT', 'Angelica Salazar ALVAREZ', 'Teresa ALVAREZ', 'Maria Isabella AMAYA', 'Lyda Catherine AMBROSE', 'Kimberly S. ANDERSON', 'Michele Kristen ANDERSON', 'Brenda Evers ANDREW', 'Jane ANDREWS', 'Julia Rothon ANDREWS', 'Tracie Marguerite ANDREWS', 'Wendi Elizabeth ANDRIANO', 'Catherine ANDRUS', 'Paula ANGEL', 'Mary Ann ANSELL', 'Mary ANTOINE', 'Theresa ANTONINI', 'Anna ANTONIO', 'Amy ARCHER-GILLIGAN', 'Alice ARDEN', 'Jodi Ann ARIAS', 'Nirmala Devi ARJUN', 'LaShanda ARMSTRONG', 'China P. ARNOLD', 'Heather ARNOLD', 'Marie Dean ARRINGTON', 'Gertraud ARZBERGER', 'Gunn-Britt ASHFIELD', 'Lisl AUMAN', 'Zakieya Latrice AVERY', 'Asuncion AVILA-VILLA', 'Shajia AYOBI']
50

In [12]:
female_gender = []

for n in clean_female:
    female_gender.append("Female")
female_df = pd.DataFrame({
    "name": clean_female,
    "gender": female_gender
})

female_df.head(50)

                         name  gender
0                    Sada ABE  Female
1        Kristi Anne ABRAHAMS  Female
2         Nicole M. ABUSHARIF  Female
3         Brittny Marie ADAMS  Female
4          Christine ADEWUNMI  Female
5               Kemi ADEYOOLA  Female
6                 Lydia ADLER  Female
7        Guen Garlejo AGUILAR  Female
8          Sara María ALDRETE  Female
9       Nasra Yussef Al-ENEZI  Female
10     Maria del Rosio ALFARO  Female
11               Melanie ALIX  Female
12   Patricia Taylor ALLANSON  Female
13               Eryn ALLEGRA  Female
14             Margaret ALLEN  Female
15         Margaret Ann ALLEN  Female
16    Shirley Elizabeth ALLEN  Female
17           Wanda Jean ALLEN  Female
18       Beverley Gail ALLITT  Female
19   Angelica Salazar ALVAREZ  Female
20             Teresa ALVAREZ  Female
21       Maria Isabella AMAYA  Female
22     Lyda Catherine AMBROSE  Female
23       Kimberly S. ANDERSON  Female
24   Michele Kristen ANDERSON  Female
25        Brenda Evers ANDREW  Female
26               Jane ANDREWS  Female
27       Julia Rothon ANDREWS  Female
28  Tracie Marguerite ANDREWS  Female
29   Wendi Elizabeth ANDRIANO  Female
30           Catherine ANDRUS  Female
31                Paula ANGEL  Female
32            Mary Ann ANSELL  Female
33               Mary ANTOINE  Female
34           Theresa ANTONINI  Female
35               Anna ANTONIO  Female
36        Amy ARCHER-GILLIGAN  Female
37                Alice ARDEN  Female
38             Jodi Ann ARIAS  Female
39         Nirmala Devi ARJUN  Female
40         LaShanda ARMSTRONG  Female
41            China P. ARNOLD  Female
42             Heather ARNOLD  Female
43       Marie Dean ARRINGTON  Female
44         Gertraud ARZBERGER  Female
45        Gunn-Britt ASHFIELD  Female
46                 Lisl AUMAN  Female
47      Zakieya Latrice AVERY  Female
48       Asuncion AVILA-VILLA  Female
49               Shajia AYOBI  Female

In [16]:
#Next I want to combine the both female and male using pd.concat to get this result https://www.geeksforgeeks.org/python/pandas-concat-function-in-python/
final_df = pd.concat([male_df, female_df], axis=0, ignore_index=True) 
#using the axis and ignore code so i can get all the rows (when i didnt use it I only saw 49) https://codegive.com/blog/pandas_ignore_index_true.php

final_df.head(270)

                      name  gender     method
0              Abbas Baqir    Male   Shooting
1                    ABBAS    Male   Shooting
2         Burton W. ABBOTT    Male  Poisoning
3        Jack Henry ABBOTT    Male   Stabbing
4     William Keith ABBOTT    Male   Shooting
..                     ...     ...        ...
265    Gunn-Britt ASHFIELD  Female        NaN
266             Lisl AUMAN  Female        NaN
267  Zakieya Latrice AVERY  Female        NaN
268   Asuncion AVILA-VILLA  Female        NaN
269           Shajia AYOBI  Female        NaN

[270 rows x 3 columns]

In [35]:
#Moving onto my next variable which is methods of killing

In [14]:
from urllib.parse import urljoin

male_links = []
male_methods = []

tags = male_soup.find_all('a', href=True)

for link in tags:
    href = link.get('href')
    x = link.get_text(" ", strip=True)

    if href and href.endswith('.htm'):
        if 'index' not in href:
            if len(x) > 3:
                x = x.replace("\n", " ")
                x = x.replace("\t", " ")
                x = " ".join(x.split())

                if x.lower() not in ["home", "last updates", "index by country"]:
                    male_links.append(urljoin(male_url, href))

male_links = male_links[:len(male_df)]

for link in male_links:
    try:
        response = requests.get(link, headers=headers)
        soup = BeautifulSoup(response.text, "html.parser")
        text = soup.get_text(" ", strip=True).lower()

        if "poison" in text or "arsenic" in text or "cyanide" in text:
            male_methods.append("Poisoning")
        elif "shoot" in text or "gun" in text or "shot" in text or "rifle" in text:
            male_methods.append("Shooting")
        elif "stab" in text or "knife" in text:
            male_methods.append("Stabbing")
        elif "strangl" in text or "suffocat" in text:
            male_methods.append("Strangulation")
        elif "bludgeon" in text or "beat" in text or "hammer" in text or "club" in text:
            male_methods.append("Bludgeoning/Beating")
        elif "axe" in text or "hatchet" in text:
            male_methods.append("Axe/Hatchet")
        elif "drown" in text:
            male_methods.append("Drowning")
        elif "fire" in text or "burn" in text:
            male_methods.append("Burning/Fire")
        else:
            male_methods.append("Unknown")

    except:
        male_methods.append("Unknown")

print(len(male_df), len(male_links), len(male_methods))

220 220 220

In [15]:
#Combining male names and method
male_df["method"] = male_methods
print(male_df[["name", "method"]].head(220).to_string())

                             name               method
0                     Abbas Baqir             Shooting
1                           ABBAS             Shooting
2                Burton W. ABBOTT            Poisoning
3               Jack Henry ABBOTT             Stabbing
4            William Keith ABBOTT             Shooting
5                   Azad ABDULLAH             Stabbing
6            Herisch Ali ABDULLAH             Shooting
7                    Ricky ABEYTA             Shooting
8                 Roderick ABEYTA             Shooting
9         Nathaniel Jamal ABRAHAM             Shooting
10                Myer ABRAMOVICH             Stabbing
11                          Elias            Poisoning
12                      ABUELAZAM            Poisoning
13    Saber & Mahmoud ABU-EL-ULLA             Shooting
14                Mumia ABU-JAMAL            Poisoning
15           Ali Hassan ABU JAMAL             Shooting
16              Elias ACEVEDO Sr.             Shooting
17              Francisco ACEVEDO        Strangulation
18             Daniel Clate ACKER             Stabbing
19               Lorne Joe ACQUIN             Stabbing
20          Robert James ACREMANT             Shooting
21        Aubrey Dennis ADAMS Jr.             Stabbing
22                   Bennie ADAMS        Strangulation
23                   Beunka ADAMS             Shooting
24                Edward J. ADAMS             Shooting
25                    James ADAMS  Bludgeoning/Beating
26                John Wade ADAMS             Stabbing
27          Dr. John Bodkin ADAMS            Poisoning
28              Richard Lee ADAMS  Bludgeoning/Beating
29          Sylvester Lewis ADAMS             Shooting
30            Timothy Wayne ADAMS             Shooting
31           William Nelson ADAMS             Stabbing
32        Dwight Dwayne ADANANDUS             Shooting
33                 Kazeem ADEYEMO             Shooting
34             Jim David ADKISSON             Shooting
35               George C. ADORNO         Burning/Fire
36                    David AFUTA             Shooting
37           Joseph Moreno AGUAYO        Strangulation
38          Jesus Ledesma AGUILAR             Shooting
39               Tonatihu AGUILAR             Shooting
40                 Jesus AGUILERA             Stabbing
41                    Nazir AHMAD             Stabbing
42                 Shahidul AHMED        Strangulation
43                   H asan AKBAR             Shooting
44                Glen Burton AKE             Shooting
45             Thomas Wayne AKERS             Stabbing
46                   Joseph Dewey            Poisoning
47                           AKIN            Poisoning
48             Stephen AKINMURELE        Strangulation
49               John Avalos ALBA             Shooting
50               Charles ALBANESE            Poisoning
51              Gameel AL-BATOUTI             Shooting
52     Charles Frederick ALBRIGHT             Shooting
53            Rodney James ALCALA             Shooting
54              John James ALCOTT             Shooting
55           Jack Edward ALDERMAN             Shooting
56           Donald Loren ALDRICH             Shooting
57                 Patrice ALÈGRE        Strangulation
58                Andre ALEXANDER             Shooting
59            Caruthers ALEXANDER             Stabbing
60                   Aaron ALEXIS             Shooting
61            Arif and Farman ALI             Shooting
62                   Michael ALIG             Shooting
63          Franklin DeWayne ALIX             Shooting
64             Jean-Pierre ALLAIN             Shooting
65         Edward Charles ALLAWAY             Shooting
66           Thomas Henry ALLAWAY  Bludgeoning/Beating
67             Clarence Ray ALLEN            Poisoning
68                    Dyson ALLEN            Poisoning
69                    Floyd ALLEN             Shooting
70             Garry Thomas ALLEN             Shooting
71                      Guy ALLEN             Stabbing
72            Howard Arthur ALLEN             Stabbing
73              John Edward ALLEN        Strangulation
74             Kerry Dimart ALLEN             Stabbing
75              Lloyd Chase ALLEN             Stabbing
76            Peter Anthony ALLEN            Poisoning
77             Quincy Javon ALLEN             Shooting
78           Stanley Edward ALLEN             Shooting
79                   Sedley ALLEY             Shooting
80         Curtis Michael ALLGIER             Shooting
81                 Shareef ALLMAN             Shooting
82      James Vernon ALLRIDGE III            Poisoning
83          Ronald Keith ALLRIDGE             Shooting
84         Sahib Lateef AL-MOSAWI             Stabbing
85       Yahya Hussein AL-RAGHWAH             Shooting
86       Charlie Mason ALSTON Jr.        Strangulation
87       P ressley Bernard ALSTON             Shooting
88               Lorenzo ALVARADO             Shooting
89          Steven Brian ALVARADO             Stabbing
90            Juan Carlos ÁLVAREZ             Shooting
91            Juan Manuel ÁLVAREZ             Stabbing
92         Manuel Machado ÁLVAREZ             Shooting
93             Billy Don ALVERSON             Shooting
94              Gary Eldon ALVORD             Shooting
95               J ohn Joe AMADOR             Shooting
96                  Abdelali AMER  Bludgeoning/Beating
97              Triston Jay AMERO             Stabbing
98                     Yigal AMIR             Shooting
99            Bernard Eugene AMOS             Shooting
100             Lowell Edwin AMOS            Poisoning
101                Nordine AMRANI             Shooting
102              Joseph D. AMRINE             Stabbing
103       Ambrosio ANALCO RAMIREZ             Shooting
104  Johan Alfred Andersson ANDER  Bludgeoning/Beating
105               Roger ANDERMATT             Stabbing
106          Allen Leroy ANDERSON              Unknown
107              Anthony ANDERSON  Bludgeoning/Beating
108           Chad Jason ANDERSON             Shooting
109           Charles L. ANDERSON             Shooting
110          Curtis Dean ANDERSON             Stabbing
111              Dale R. ANDERSON        Strangulation
112                David ANDERSON             Shooting
113       Frank Winfield ANDERSON             Shooting
114             Fred ANDERSON Jr.             Shooting
115                Jesse ANDERSON             Shooting
116           Johnny Ray ANDERSON             Shooting
117         Larry Norman ANDERSON             Shooting
118         Michael John ANDERSON             Shooting
119        Newton Burton ANDERSON             Shooting
120        Percy Charles ANDERSON              Unknown
121       Richard Harold ANDERSON             Shooting
122         Robert James ANDERSON             Shooting
123         Robert Leroy ANDERSON             Shooting
124     Stephen Lawrence ANDERSON             Shooting
125        Stephen Wayne ANDERSON             Shooting
126          Terrance L. ANDERSON             Shooting
127               Richard ANDRADE            Poisoning
128               Rogelio ANDRADE             Shooting
129         James Douglas ANDREWS              Unknown
130          Joshua Wayne ANDREWS             Shooting
131         Larry Donnell ANDREWS            Poisoning
132            Lowell Lee ANDREWS            Poisoning
133         Ralph Raymond ANDREWS             Shooting
134               William ANDREWS             Shooting
135                Terence ANDRUS             Shooting
136                Richard ANGELO            Poisoning
137     Fritz Heinrich ANGERSTEIN             Shooting
138      R oger Nicholas ANGLETON             Shooting
139                  Klaas ANNINK              Unknown
140               Artem ANOUFRIEV             Stabbing
141          D avid Lamar ANTHONY              Unknown
142                  Abram ANTONE             Shooting
143                Anthony ANTONE             Shooting
144               Mauro ANTONELLO             Shooting
145               Narding ANZURES             Stabbing
146                 Michael APELT             Stabbing
147                    Rudi APELT             Stabbing
148         Siavosh Rahmani AQDAM             Shooting
149                   Eugene ARAM             Shooting
150          Arturo Daniel ARANDA             Shooting
151    Guillermo Octavio ARBELAEZ             Drowning
152      Roscoe Conkling ARBUCKLE             Shooting
153         Francisco ARCE MONTES             Stabbing
154                 Jonathan ARCE             Shooting
155                  James ARCENE             Shooting
156              Robin Lee ARCHER             Shooting
157          William Dale ARCHERD            Poisoning
158          T hayne H. ARCHIBALD             Shooting
159    Gilbert Eugenio ARCHIBEQUE             Shooting
160             Gregorio ARELLANO             Shooting
161              Jeffrey ARENBURG             Shooting
162             Roberto ARGÜELLES             Shooting
163          Gumaro de Dios ARIAS             Shooting
164                   Pedro ARIAS             Shooting
165                 David ARISMAN             Shooting
166                 Jackie ARKLÖV             Shooting
167        Anthony Paul ARKWRIGHT             Stabbing
168     Charles W. ARMENTROUT III  Bludgeoning/Beating
169       Herbert Rowse ARMSTRONG            Poisoning
170           John Eric ARMSTRONG             Shooting
171            Lancelot ARMSTRONG             Shooting
172            Pleasant ARMSTRONG             Shooting
173          Ralph Dale ARMSTRONG             Shooting
174         Shad Daniel ARMSTRONG             Shooting
175       Shaun Anthony ARMSTRONG             Shooting
176         Jermarr Carlos ARNOLD             Shooting
177                John D. ARNOLD             Stabbing
178                     Levi ARON             Shooting
179            R andy ARROYO BAEZ             Shooting
180                  Rahan ARSHAD             Stabbing
181              M ark Sam ARTHUR             Shooting
182                  Tommy ARTHUR             Shooting
183         Dante Wyndham ARTHURS        Strangulation
184              Kevin Lloyd ARTZ  Bludgeoning/Beating
185                 Shoko ASAHARA            Poisoning
186                Kojiro ASAKURA  Bludgeoning/Beating
187               Mark James ASAY             Shooting
188           Larry Gene ASHBROOK             Shooting
189           Lazale Delane ASHBY             Shooting
190              Troy Adam ASHMUS             Shooting
191          Herman Dale ASHWORTH  Bludgeoning/Beating
192               Valery ASRATYAN            Poisoning
193            Andrew Simon ASTON             Shooting
194               Samuel ATHERLEY  Bludgeoning/Beating
195          Benjamin Tony ATKINS             Shooting
196           Daryl Renard ATKINS             Shooting
197     Frederick Benjamin ATKINS             Stabbing
198          Joseph Ernest ATKINS             Shooting
199     Philliph Alexander ATKINS             Shooting
200           David Edward ATTIAS             Shooting
201           Jeffrey Lee ATWATER             Stabbing
202           Frank Jarvis ATWOOD             Stabbing
203         Robert Ronald ATWORTH             Shooting
204                J ohn AUSONIUS             Shooting
205                 Ernest AUSTIN        Strangulation
206            Perry Allen AUSTIN             Stabbing
207             James David AUTRY             Shooting
208            Pekka-Eric AUVINEN             Shooting
209              Jorjik AVANESIAN             Stabbing
210            Rufus Lee AVERHART             Shooting
211                  Steven AVERY             Stabbing
212               Alejandro AVILA             Stabbing
213          Gabriel Adrian AVILA             Shooting
214           Rigoberto AVILA Jr.             Shooting
215      Dr. Arnold Asher AXILROD             Stabbing
216           Erik Salvador AYALA             Shooting
217        C arlos Manuel AYESTAS        Strangulation
218                 Anthony AYRES             Shooting
219                 Johnson AZIGA             Shooting

In [17]:
from urllib.parse import urljoin

female_links = []
female_methods = []

tags = female_soup.find_all('a', href=True)

for link in tags:
    href = link.get('href')
    x = link.get_text(" ", strip=True)

    if href and href.endswith('.htm'):
        if 'index' not in href:
            if len(x) > 3:
                x = x.replace("\n", " ")
                x = x.replace("\t", " ")
                x = " ".join(x.split())

                if x.lower() not in ["home", "last updates", "index by country"]:
                    female_links.append(urljoin(female_url, href))

# match length with your dataframe
female_links = female_links[:len(female_df)]

# same keyword classification
for link in female_links:
    try:
        response = requests.get(link, headers=headers)
        soup = BeautifulSoup(response.text, "html.parser")
        text = soup.get_text(" ", strip=True).lower()

        if "poison" in text or "arsenic" in text or "cyanide" in text:
            female_methods.append("Poisoning")
        elif "shoot" in text or "gun" in text or "shot" in text or "rifle" in text:
            female_methods.append("Shooting")
        elif "stab" in text or "knife" in text:
            female_methods.append("Stabbing")
        elif "strangl" in text or "suffocat" in text:
            female_methods.append("Strangulation")
        elif "bludgeon" in text or "beat" in text or "hammer" in text or "club" in text:
            female_methods.append("Bludgeoning/Beating")
        elif "axe" in text or "hatchet" in text:
            female_methods.append("Axe/Hatchet")
        elif "drown" in text:
            female_methods.append("Drowning")
        elif "fire" in text or "burn" in text:
            female_methods.append("Burning/Fire")
        else:
            female_methods.append("Unknown")

    except:
        female_methods.append("Unknown")

print(len(female_df), len(female_links), len(female_methods))

50 50 50

In [18]:
female_df["method"] = female_methods
print(female_df[["name", "method"]].head(50).to_string())

                         name               method
0                    Sada ABE            Poisoning
1        Kristi Anne ABRAHAMS             Stabbing
2         Nicole M. ABUSHARIF             Shooting
3         Brittny Marie ADAMS             Shooting
4          Christine ADEWUNMI             Shooting
5               Kemi ADEYOOLA            Poisoning
6                 Lydia ADLER  Bludgeoning/Beating
7        Guen Garlejo AGUILAR            Poisoning
8          Sara María ALDRETE             Shooting
9       Nasra Yussef Al-ENEZI             Stabbing
10     Maria del Rosio ALFARO             Shooting
11               Melanie ALIX         Burning/Fire
12   Patricia Taylor ALLANSON            Poisoning
13               Eryn ALLEGRA        Strangulation
14             Margaret ALLEN             Stabbing
15         Margaret Ann ALLEN             Shooting
16    Shirley Elizabeth ALLEN            Poisoning
17           Wanda Jean ALLEN            Poisoning
18       Beverley Gail ALLITT            Poisoning
19   Angelica Salazar ALVAREZ        Strangulation
20             Teresa ALVAREZ             Stabbing
21       Maria Isabella AMAYA             Stabbing
22     Lyda Catherine AMBROSE            Poisoning
23       Kimberly S. ANDERSON             Shooting
24   Michele Kristen ANDERSON             Shooting
25        Brenda Evers ANDREW            Poisoning
26               Jane ANDREWS             Stabbing
27       Julia Rothon ANDREWS             Shooting
28  Tracie Marguerite ANDREWS             Stabbing
29   Wendi Elizabeth ANDRIANO            Poisoning
30           Catherine ANDRUS  Bludgeoning/Beating
31                Paula ANGEL             Stabbing
32            Mary Ann ANSELL            Poisoning
33               Mary ANTOINE             Stabbing
34           Theresa ANTONINI  Bludgeoning/Beating
35               Anna ANTONIO             Shooting
36        Amy ARCHER-GILLIGAN            Poisoning
37                Alice ARDEN            Poisoning
38             Jodi Ann ARIAS             Shooting
39         Nirmala Devi ARJUN              Unknown
40         LaShanda ARMSTRONG             Stabbing
41            China P. ARNOLD             Shooting
42             Heather ARNOLD  Bludgeoning/Beating
43       Marie Dean ARRINGTON             Shooting
44         Gertraud ARZBERGER             Shooting
45        Gunn-Britt ASHFIELD             Shooting
46                 Lisl AUMAN            Poisoning
47      Zakieya Latrice AVERY             Stabbing
48       Asuncion AVILA-VILLA  Bludgeoning/Beating
49               Shajia AYOBI             Shooting

In [19]:
#Combining both genders,names,and methods
final_df = pd.concat([male_df, female_df], ignore_index=True)

print(final_df[["name", "gender", "method"]].head(270).to_string())

                             name  gender               method
0                     Abbas Baqir    Male             Shooting
1                           ABBAS    Male             Shooting
2                Burton W. ABBOTT    Male            Poisoning
3               Jack Henry ABBOTT    Male             Stabbing
4            William Keith ABBOTT    Male             Shooting
5                   Azad ABDULLAH    Male             Stabbing
6            Herisch Ali ABDULLAH    Male             Shooting
7                    Ricky ABEYTA    Male             Shooting
8                 Roderick ABEYTA    Male             Shooting
9         Nathaniel Jamal ABRAHAM    Male             Shooting
10                Myer ABRAMOVICH    Male             Stabbing
11                          Elias    Male            Poisoning
12                      ABUELAZAM    Male            Poisoning
13    Saber & Mahmoud ABU-EL-ULLA    Male             Shooting
14                Mumia ABU-JAMAL    Male            Poisoning
15           Ali Hassan ABU JAMAL    Male             Shooting
16              Elias ACEVEDO Sr.    Male             Shooting
17              Francisco ACEVEDO    Male        Strangulation
18             Daniel Clate ACKER    Male             Stabbing
19               Lorne Joe ACQUIN    Male             Stabbing
20          Robert James ACREMANT    Male             Shooting
21        Aubrey Dennis ADAMS Jr.    Male             Stabbing
22                   Bennie ADAMS    Male        Strangulation
23                   Beunka ADAMS    Male             Shooting
24                Edward J. ADAMS    Male             Shooting
25                    James ADAMS    Male  Bludgeoning/Beating
26                John Wade ADAMS    Male             Stabbing
27          Dr. John Bodkin ADAMS    Male            Poisoning
28              Richard Lee ADAMS    Male  Bludgeoning/Beating
29          Sylvester Lewis ADAMS    Male             Shooting
30            Timothy Wayne ADAMS    Male             Shooting
31           William Nelson ADAMS    Male             Stabbing
32        Dwight Dwayne ADANANDUS    Male             Shooting
33                 Kazeem ADEYEMO    Male             Shooting
34             Jim David ADKISSON    Male             Shooting
35               George C. ADORNO    Male         Burning/Fire
36                    David AFUTA    Male             Shooting
37           Joseph Moreno AGUAYO    Male        Strangulation
38          Jesus Ledesma AGUILAR    Male             Shooting
39               Tonatihu AGUILAR    Male             Shooting
40                 Jesus AGUILERA    Male             Stabbing
41                    Nazir AHMAD    Male             Stabbing
42                 Shahidul AHMED    Male        Strangulation
43                   H asan AKBAR    Male             Shooting
44                Glen Burton AKE    Male             Shooting
45             Thomas Wayne AKERS    Male             Stabbing
46                   Joseph Dewey    Male            Poisoning
47                           AKIN    Male            Poisoning
48             Stephen AKINMURELE    Male        Strangulation
49               John Avalos ALBA    Male             Shooting
50               Charles ALBANESE    Male            Poisoning
51              Gameel AL-BATOUTI    Male             Shooting
52     Charles Frederick ALBRIGHT    Male             Shooting
53            Rodney James ALCALA    Male             Shooting
54              John James ALCOTT    Male             Shooting
55           Jack Edward ALDERMAN    Male             Shooting
56           Donald Loren ALDRICH    Male             Shooting
57                 Patrice ALÈGRE    Male        Strangulation
58                Andre ALEXANDER    Male             Shooting
59            Caruthers ALEXANDER    Male             Stabbing
60                   Aaron ALEXIS    Male             Shooting
61            Arif and Farman ALI    Male             Shooting
62                   Michael ALIG    Male             Shooting
63          Franklin DeWayne ALIX    Male             Shooting
64             Jean-Pierre ALLAIN    Male             Shooting
65         Edward Charles ALLAWAY    Male             Shooting
66           Thomas Henry ALLAWAY    Male  Bludgeoning/Beating
67             Clarence Ray ALLEN    Male            Poisoning
68                    Dyson ALLEN    Male            Poisoning
69                    Floyd ALLEN    Male             Shooting
70             Garry Thomas ALLEN    Male             Shooting
71                      Guy ALLEN    Male             Stabbing
72            Howard Arthur ALLEN    Male             Stabbing
73              John Edward ALLEN    Male        Strangulation
74             Kerry Dimart ALLEN    Male             Stabbing
75              Lloyd Chase ALLEN    Male             Stabbing
76            Peter Anthony ALLEN    Male            Poisoning
77             Quincy Javon ALLEN    Male             Shooting
78           Stanley Edward ALLEN    Male             Shooting
79                   Sedley ALLEY    Male             Shooting
80         Curtis Michael ALLGIER    Male             Shooting
81                 Shareef ALLMAN    Male             Shooting
82      James Vernon ALLRIDGE III    Male            Poisoning
83          Ronald Keith ALLRIDGE    Male             Shooting
84         Sahib Lateef AL-MOSAWI    Male             Stabbing
85       Yahya Hussein AL-RAGHWAH    Male             Shooting
86       Charlie Mason ALSTON Jr.    Male        Strangulation
87       P ressley Bernard ALSTON    Male             Shooting
88               Lorenzo ALVARADO    Male             Shooting
89          Steven Brian ALVARADO    Male             Stabbing
90            Juan Carlos ÁLVAREZ    Male             Shooting
91            Juan Manuel ÁLVAREZ    Male             Stabbing
92         Manuel Machado ÁLVAREZ    Male             Shooting
93             Billy Don ALVERSON    Male             Shooting
94              Gary Eldon ALVORD    Male             Shooting
95               J ohn Joe AMADOR    Male             Shooting
96                  Abdelali AMER    Male  Bludgeoning/Beating
97              Triston Jay AMERO    Male             Stabbing
98                     Yigal AMIR    Male             Shooting
99            Bernard Eugene AMOS    Male             Shooting
100             Lowell Edwin AMOS    Male            Poisoning
101                Nordine AMRANI    Male             Shooting
102              Joseph D. AMRINE    Male             Stabbing
103       Ambrosio ANALCO RAMIREZ    Male             Shooting
104  Johan Alfred Andersson ANDER    Male  Bludgeoning/Beating
105               Roger ANDERMATT    Male             Stabbing
106          Allen Leroy ANDERSON    Male              Unknown
107              Anthony ANDERSON    Male  Bludgeoning/Beating
108           Chad Jason ANDERSON    Male             Shooting
109           Charles L. ANDERSON    Male             Shooting
110          Curtis Dean ANDERSON    Male             Stabbing
111              Dale R. ANDERSON    Male        Strangulation
112                David ANDERSON    Male             Shooting
113       Frank Winfield ANDERSON    Male             Shooting
114             Fred ANDERSON Jr.    Male             Shooting
115                Jesse ANDERSON    Male             Shooting
116           Johnny Ray ANDERSON    Male             Shooting
117         Larry Norman ANDERSON    Male             Shooting
118         Michael John ANDERSON    Male             Shooting
119        Newton Burton ANDERSON    Male             Shooting
120        Percy Charles ANDERSON    Male              Unknown
121       Richard Harold ANDERSON    Male             Shooting
122         Robert James ANDERSON    Male             Shooting
123         Robert Leroy ANDERSON    Male             Shooting
124     Stephen Lawrence ANDERSON    Male             Shooting
125        Stephen Wayne ANDERSON    Male             Shooting
126          Terrance L. ANDERSON    Male             Shooting
127               Richard ANDRADE    Male            Poisoning
128               Rogelio ANDRADE    Male             Shooting
129         James Douglas ANDREWS    Male              Unknown
130          Joshua Wayne ANDREWS    Male             Shooting
131         Larry Donnell ANDREWS    Male            Poisoning
132            Lowell Lee ANDREWS    Male            Poisoning
133         Ralph Raymond ANDREWS    Male             Shooting
134               William ANDREWS    Male             Shooting
135                Terence ANDRUS    Male             Shooting
136                Richard ANGELO    Male            Poisoning
137     Fritz Heinrich ANGERSTEIN    Male             Shooting
138      R oger Nicholas ANGLETON    Male             Shooting
139                  Klaas ANNINK    Male              Unknown
140               Artem ANOUFRIEV    Male             Stabbing
141          D avid Lamar ANTHONY    Male              Unknown
142                  Abram ANTONE    Male             Shooting
143                Anthony ANTONE    Male             Shooting
144               Mauro ANTONELLO    Male             Shooting
145               Narding ANZURES    Male             Stabbing
146                 Michael APELT    Male             Stabbing
147                    Rudi APELT    Male             Stabbing
148         Siavosh Rahmani AQDAM    Male             Shooting
149                   Eugene ARAM    Male             Shooting
150          Arturo Daniel ARANDA    Male             Shooting
151    Guillermo Octavio ARBELAEZ    Male             Drowning
152      Roscoe Conkling ARBUCKLE    Male             Shooting
153         Francisco ARCE MONTES    Male             Stabbing
154                 Jonathan ARCE    Male             Shooting
155                  James ARCENE    Male             Shooting
156              Robin Lee ARCHER    Male             Shooting
157          William Dale ARCHERD    Male            Poisoning
158          T hayne H. ARCHIBALD    Male             Shooting
159    Gilbert Eugenio ARCHIBEQUE    Male             Shooting
160             Gregorio ARELLANO    Male             Shooting
161              Jeffrey ARENBURG    Male             Shooting
162             Roberto ARGÜELLES    Male             Shooting
163          Gumaro de Dios ARIAS    Male             Shooting
164                   Pedro ARIAS    Male             Shooting
165                 David ARISMAN    Male             Shooting
166                 Jackie ARKLÖV    Male             Shooting
167        Anthony Paul ARKWRIGHT    Male             Stabbing
168     Charles W. ARMENTROUT III    Male  Bludgeoning/Beating
169       Herbert Rowse ARMSTRONG    Male            Poisoning
170           John Eric ARMSTRONG    Male             Shooting
171            Lancelot ARMSTRONG    Male             Shooting
172            Pleasant ARMSTRONG    Male             Shooting
173          Ralph Dale ARMSTRONG    Male             Shooting
174         Shad Daniel ARMSTRONG    Male             Shooting
175       Shaun Anthony ARMSTRONG    Male             Shooting
176         Jermarr Carlos ARNOLD    Male             Shooting
177                John D. ARNOLD    Male             Stabbing
178                     Levi ARON    Male             Shooting
179            R andy ARROYO BAEZ    Male             Shooting
180                  Rahan ARSHAD    Male             Stabbing
181              M ark Sam ARTHUR    Male             Shooting
182                  Tommy ARTHUR    Male             Shooting
183         Dante Wyndham ARTHURS    Male        Strangulation
184              Kevin Lloyd ARTZ    Male  Bludgeoning/Beating
185                 Shoko ASAHARA    Male            Poisoning
186                Kojiro ASAKURA    Male  Bludgeoning/Beating
187               Mark James ASAY    Male             Shooting
188           Larry Gene ASHBROOK    Male             Shooting
189           Lazale Delane ASHBY    Male             Shooting
190              Troy Adam ASHMUS    Male             Shooting
191          Herman Dale ASHWORTH    Male  Bludgeoning/Beating
192               Valery ASRATYAN    Male            Poisoning
193            Andrew Simon ASTON    Male             Shooting
194               Samuel ATHERLEY    Male  Bludgeoning/Beating
195          Benjamin Tony ATKINS    Male             Shooting
196           Daryl Renard ATKINS    Male             Shooting
197     Frederick Benjamin ATKINS    Male             Stabbing
198          Joseph Ernest ATKINS    Male             Shooting
199     Philliph Alexander ATKINS    Male             Shooting
200           David Edward ATTIAS    Male             Shooting
201           Jeffrey Lee ATWATER    Male             Stabbing
202           Frank Jarvis ATWOOD    Male             Stabbing
203         Robert Ronald ATWORTH    Male             Shooting
204                J ohn AUSONIUS    Male             Shooting
205                 Ernest AUSTIN    Male        Strangulation
206            Perry Allen AUSTIN    Male             Stabbing
207             James David AUTRY    Male             Shooting
208            Pekka-Eric AUVINEN    Male             Shooting
209              Jorjik AVANESIAN    Male             Stabbing
210            Rufus Lee AVERHART    Male             Shooting
211                  Steven AVERY    Male             Stabbing
212               Alejandro AVILA    Male             Stabbing
213          Gabriel Adrian AVILA    Male             Shooting
214           Rigoberto AVILA Jr.    Male             Shooting
215      Dr. Arnold Asher AXILROD    Male             Stabbing
216           Erik Salvador AYALA    Male             Shooting
217        C arlos Manuel AYESTAS    Male        Strangulation
218                 Anthony AYRES    Male             Shooting
219                 Johnson AZIGA    Male             Shooting
220                      Sada ABE  Female            Poisoning
221          Kristi Anne ABRAHAMS  Female             Stabbing
222           Nicole M. ABUSHARIF  Female             Shooting
223           Brittny Marie ADAMS  Female             Shooting
224            Christine ADEWUNMI  Female             Shooting
225                 Kemi ADEYOOLA  Female            Poisoning
226                   Lydia ADLER  Female  Bludgeoning/Beating
227          Guen Garlejo AGUILAR  Female            Poisoning
228            Sara María ALDRETE  Female             Shooting
229         Nasra Yussef Al-ENEZI  Female             Stabbing
230        Maria del Rosio ALFARO  Female             Shooting
231                  Melanie ALIX  Female         Burning/Fire
232      Patricia Taylor ALLANSON  Female            Poisoning
233                  Eryn ALLEGRA  Female        Strangulation
234                Margaret ALLEN  Female             Stabbing
235            Margaret Ann ALLEN  Female             Shooting
236       Shirley Elizabeth ALLEN  Female            Poisoning
237              Wanda Jean ALLEN  Female            Poisoning
238          Beverley Gail ALLITT  Female            Poisoning
239      Angelica Salazar ALVAREZ  Female        Strangulation
240                Teresa ALVAREZ  Female             Stabbing
241          Maria Isabella AMAYA  Female             Stabbing
242        Lyda Catherine AMBROSE  Female            Poisoning
243          Kimberly S. ANDERSON  Female             Shooting
244      Michele Kristen ANDERSON  Female             Shooting
245           Brenda Evers ANDREW  Female            Poisoning
246                  Jane ANDREWS  Female             Stabbing
247          Julia Rothon ANDREWS  Female             Shooting
248     Tracie Marguerite ANDREWS  Female             Stabbing
249      Wendi Elizabeth ANDRIANO  Female            Poisoning
250              Catherine ANDRUS  Female  Bludgeoning/Beating
251                   Paula ANGEL  Female             Stabbing
252               Mary Ann ANSELL  Female            Poisoning
253                  Mary ANTOINE  Female             Stabbing
254              Theresa ANTONINI  Female  Bludgeoning/Beating
255                  Anna ANTONIO  Female             Shooting
256           Amy ARCHER-GILLIGAN  Female            Poisoning
257                   Alice ARDEN  Female            Poisoning
258                Jodi Ann ARIAS  Female             Shooting
259            Nirmala Devi ARJUN  Female              Unknown
260            LaShanda ARMSTRONG  Female             Stabbing
261               China P. ARNOLD  Female             Shooting
262                Heather ARNOLD  Female  Bludgeoning/Beating
263          Marie Dean ARRINGTON  Female             Shooting
264            Gertraud ARZBERGER  Female             Shooting
265           Gunn-Britt ASHFIELD  Female             Shooting
266                    Lisl AUMAN  Female            Poisoning
267         Zakieya Latrice AVERY  Female             Stabbing
268          Asuncion AVILA-VILLA  Female  Bludgeoning/Beating
269                  Shajia AYOBI  Female             Shooting

In [20]:
#Now I want to see the number for each method by gender
method_counts = final_df.groupby(["gender", "method"]).size()

print(method_counts)

gender  method
Female  Bludgeoning/Beating      5
        Burning/Fire             1
        Poisoning               14
        Shooting                16
        Stabbing                11
        Strangulation            2
        Unknown                  1
Male    Bludgeoning/Beating     11
        Burning/Fire             1
        Drowning                 1
        Poisoning               21
        Shooting               130
        Stabbing                39
        Strangulation           12
        Unknown                  5
dtype: int64

In [ ]:
#Not sure why unknown is showing when I didnt have that in my table... (maybe so its not bias?)
#Most common method for women is shooting
#Most common method for men is also shooting 
#So from this is shows men and women both use shooting more in conducting their kills. I honsetly thought for women it would be poison since women usally conduct less messy crimes.

In [ ]:
#Next I am adding my new variable which is violent vs nonviolent crimes

In [21]:
violent_vs_nonviolent = []
#I might move drowning to non-violent not sure yet. I am basing this off of how messy the crime is such as blood. But, might need to change this with further research.
for m in final_df["method"]:
    if m == "Poisoning":
        violent_vs_nonviolent.append("Non-violent")
        
    elif m in ["Shooting", "Stabbing", "Strangulation", "Bludgeoning/Beating", "Axe/Hatchet", "Drowning", "Burning/Fire"]:
        violent_vs_nonviolent.append("Violent")
        
    else:
        violent_vs_nonviolent.append("Unknown")

In [22]:
final_df["violent_vs_nonviolent"] = violent_vs_nonviolent

In [23]:
print(final_df[["name", "gender", "method", "violent_vs_nonviolent"]].head(270).to_string())

                             name  gender               method violent_vs_nonviolent
0                     Abbas Baqir    Male             Shooting               Violent
1                           ABBAS    Male             Shooting               Violent
2                Burton W. ABBOTT    Male            Poisoning           Non-violent
3               Jack Henry ABBOTT    Male             Stabbing               Violent
4            William Keith ABBOTT    Male             Shooting               Violent
5                   Azad ABDULLAH    Male             Stabbing               Violent
6            Herisch Ali ABDULLAH    Male             Shooting               Violent
7                    Ricky ABEYTA    Male             Shooting               Violent
8                 Roderick ABEYTA    Male             Shooting               Violent
9         Nathaniel Jamal ABRAHAM    Male             Shooting               Violent
10                Myer ABRAMOVICH    Male             Stabbing               Violent
11                          Elias    Male            Poisoning           Non-violent
12                      ABUELAZAM    Male            Poisoning           Non-violent
13    Saber & Mahmoud ABU-EL-ULLA    Male             Shooting               Violent
14                Mumia ABU-JAMAL    Male            Poisoning           Non-violent
15           Ali Hassan ABU JAMAL    Male             Shooting               Violent
16              Elias ACEVEDO Sr.    Male             Shooting               Violent
17              Francisco ACEVEDO    Male        Strangulation               Violent
18             Daniel Clate ACKER    Male             Stabbing               Violent
19               Lorne Joe ACQUIN    Male             Stabbing               Violent
20          Robert James ACREMANT    Male             Shooting               Violent
21        Aubrey Dennis ADAMS Jr.    Male             Stabbing               Violent
22                   Bennie ADAMS    Male        Strangulation               Violent
23                   Beunka ADAMS    Male             Shooting               Violent
24                Edward J. ADAMS    Male             Shooting               Violent
25                    James ADAMS    Male  Bludgeoning/Beating               Violent
26                John Wade ADAMS    Male             Stabbing               Violent
27          Dr. John Bodkin ADAMS    Male            Poisoning           Non-violent
28              Richard Lee ADAMS    Male  Bludgeoning/Beating               Violent
29          Sylvester Lewis ADAMS    Male             Shooting               Violent
30            Timothy Wayne ADAMS    Male             Shooting               Violent
31           William Nelson ADAMS    Male             Stabbing               Violent
32        Dwight Dwayne ADANANDUS    Male             Shooting               Violent
33                 Kazeem ADEYEMO    Male             Shooting               Violent
34             Jim David ADKISSON    Male             Shooting               Violent
35               George C. ADORNO    Male         Burning/Fire               Violent
36                    David AFUTA    Male             Shooting               Violent
37           Joseph Moreno AGUAYO    Male        Strangulation               Violent
38          Jesus Ledesma AGUILAR    Male             Shooting               Violent
39               Tonatihu AGUILAR    Male             Shooting               Violent
40                 Jesus AGUILERA    Male             Stabbing               Violent
41                    Nazir AHMAD    Male             Stabbing               Violent
42                 Shahidul AHMED    Male        Strangulation               Violent
43                   H asan AKBAR    Male             Shooting               Violent
44                Glen Burton AKE    Male             Shooting               Violent
45             Thomas Wayne AKERS    Male             Stabbing               Violent
46                   Joseph Dewey    Male            Poisoning           Non-violent
47                           AKIN    Male            Poisoning           Non-violent
48             Stephen AKINMURELE    Male        Strangulation               Violent
49               John Avalos ALBA    Male             Shooting               Violent
50               Charles ALBANESE    Male            Poisoning           Non-violent
51              Gameel AL-BATOUTI    Male             Shooting               Violent
52     Charles Frederick ALBRIGHT    Male             Shooting               Violent
53            Rodney James ALCALA    Male             Shooting               Violent
54              John James ALCOTT    Male             Shooting               Violent
55           Jack Edward ALDERMAN    Male             Shooting               Violent
56           Donald Loren ALDRICH    Male             Shooting               Violent
57                 Patrice ALÈGRE    Male        Strangulation               Violent
58                Andre ALEXANDER    Male             Shooting               Violent
59            Caruthers ALEXANDER    Male             Stabbing               Violent
60                   Aaron ALEXIS    Male             Shooting               Violent
61            Arif and Farman ALI    Male             Shooting               Violent
62                   Michael ALIG    Male             Shooting               Violent
63          Franklin DeWayne ALIX    Male             Shooting               Violent
64             Jean-Pierre ALLAIN    Male             Shooting               Violent
65         Edward Charles ALLAWAY    Male             Shooting               Violent
66           Thomas Henry ALLAWAY    Male  Bludgeoning/Beating               Violent
67             Clarence Ray ALLEN    Male            Poisoning           Non-violent
68                    Dyson ALLEN    Male            Poisoning           Non-violent
69                    Floyd ALLEN    Male             Shooting               Violent
70             Garry Thomas ALLEN    Male             Shooting               Violent
71                      Guy ALLEN    Male             Stabbing               Violent
72            Howard Arthur ALLEN    Male             Stabbing               Violent
73              John Edward ALLEN    Male        Strangulation               Violent
74             Kerry Dimart ALLEN    Male             Stabbing               Violent
75              Lloyd Chase ALLEN    Male             Stabbing               Violent
76            Peter Anthony ALLEN    Male            Poisoning           Non-violent
77             Quincy Javon ALLEN    Male             Shooting               Violent
78           Stanley Edward ALLEN    Male             Shooting               Violent
79                   Sedley ALLEY    Male             Shooting               Violent
80         Curtis Michael ALLGIER    Male             Shooting               Violent
81                 Shareef ALLMAN    Male             Shooting               Violent
82      James Vernon ALLRIDGE III    Male            Poisoning           Non-violent
83          Ronald Keith ALLRIDGE    Male             Shooting               Violent
84         Sahib Lateef AL-MOSAWI    Male             Stabbing               Violent
85       Yahya Hussein AL-RAGHWAH    Male             Shooting               Violent
86       Charlie Mason ALSTON Jr.    Male        Strangulation               Violent
87       P ressley Bernard ALSTON    Male             Shooting               Violent
88               Lorenzo ALVARADO    Male             Shooting               Violent
89          Steven Brian ALVARADO    Male             Stabbing               Violent
90            Juan Carlos ÁLVAREZ    Male             Shooting               Violent
91            Juan Manuel ÁLVAREZ    Male             Stabbing               Violent
92         Manuel Machado ÁLVAREZ    Male             Shooting               Violent
93             Billy Don ALVERSON    Male             Shooting               Violent
94              Gary Eldon ALVORD    Male             Shooting               Violent
95               J ohn Joe AMADOR    Male             Shooting               Violent
96                  Abdelali AMER    Male  Bludgeoning/Beating               Violent
97              Triston Jay AMERO    Male             Stabbing               Violent
98                     Yigal AMIR    Male             Shooting               Violent
99            Bernard Eugene AMOS    Male             Shooting               Violent
100             Lowell Edwin AMOS    Male            Poisoning           Non-violent
101                Nordine AMRANI    Male             Shooting               Violent
102              Joseph D. AMRINE    Male             Stabbing               Violent
103       Ambrosio ANALCO RAMIREZ    Male             Shooting               Violent
104  Johan Alfred Andersson ANDER    Male  Bludgeoning/Beating               Violent
105               Roger ANDERMATT    Male             Stabbing               Violent
106          Allen Leroy ANDERSON    Male              Unknown               Unknown
107              Anthony ANDERSON    Male  Bludgeoning/Beating               Violent
108           Chad Jason ANDERSON    Male             Shooting               Violent
109           Charles L. ANDERSON    Male             Shooting               Violent
110          Curtis Dean ANDERSON    Male             Stabbing               Violent
111              Dale R. ANDERSON    Male        Strangulation               Violent
112                David ANDERSON    Male             Shooting               Violent
113       Frank Winfield ANDERSON    Male             Shooting               Violent
114             Fred ANDERSON Jr.    Male             Shooting               Violent
115                Jesse ANDERSON    Male             Shooting               Violent
116           Johnny Ray ANDERSON    Male             Shooting               Violent
117         Larry Norman ANDERSON    Male             Shooting               Violent
118         Michael John ANDERSON    Male             Shooting               Violent
119        Newton Burton ANDERSON    Male             Shooting               Violent
120        Percy Charles ANDERSON    Male              Unknown               Unknown
121       Richard Harold ANDERSON    Male             Shooting               Violent
122         Robert James ANDERSON    Male             Shooting               Violent
123         Robert Leroy ANDERSON    Male             Shooting               Violent
124     Stephen Lawrence ANDERSON    Male             Shooting               Violent
125        Stephen Wayne ANDERSON    Male             Shooting               Violent
126          Terrance L. ANDERSON    Male             Shooting               Violent
127               Richard ANDRADE    Male            Poisoning           Non-violent
128               Rogelio ANDRADE    Male             Shooting               Violent
129         James Douglas ANDREWS    Male              Unknown               Unknown
130          Joshua Wayne ANDREWS    Male             Shooting               Violent
131         Larry Donnell ANDREWS    Male            Poisoning           Non-violent
132            Lowell Lee ANDREWS    Male            Poisoning           Non-violent
133         Ralph Raymond ANDREWS    Male             Shooting               Violent
134               William ANDREWS    Male             Shooting               Violent
135                Terence ANDRUS    Male             Shooting               Violent
136                Richard ANGELO    Male            Poisoning           Non-violent
137     Fritz Heinrich ANGERSTEIN    Male             Shooting               Violent
138      R oger Nicholas ANGLETON    Male             Shooting               Violent
139                  Klaas ANNINK    Male              Unknown               Unknown
140               Artem ANOUFRIEV    Male             Stabbing               Violent
141          D avid Lamar ANTHONY    Male              Unknown               Unknown
142                  Abram ANTONE    Male             Shooting               Violent
143                Anthony ANTONE    Male             Shooting               Violent
144               Mauro ANTONELLO    Male             Shooting               Violent
145               Narding ANZURES    Male             Stabbing               Violent
146                 Michael APELT    Male             Stabbing               Violent
147                    Rudi APELT    Male             Stabbing               Violent
148         Siavosh Rahmani AQDAM    Male             Shooting               Violent
149                   Eugene ARAM    Male             Shooting               Violent
150          Arturo Daniel ARANDA    Male             Shooting               Violent
151    Guillermo Octavio ARBELAEZ    Male             Drowning               Violent
152      Roscoe Conkling ARBUCKLE    Male             Shooting               Violent
153         Francisco ARCE MONTES    Male             Stabbing               Violent
154                 Jonathan ARCE    Male             Shooting               Violent
155                  James ARCENE    Male             Shooting               Violent
156              Robin Lee ARCHER    Male             Shooting               Violent
157          William Dale ARCHERD    Male            Poisoning           Non-violent
158          T hayne H. ARCHIBALD    Male             Shooting               Violent
159    Gilbert Eugenio ARCHIBEQUE    Male             Shooting               Violent
160             Gregorio ARELLANO    Male             Shooting               Violent
161              Jeffrey ARENBURG    Male             Shooting               Violent
162             Roberto ARGÜELLES    Male             Shooting               Violent
163          Gumaro de Dios ARIAS    Male             Shooting               Violent
164                   Pedro ARIAS    Male             Shooting               Violent
165                 David ARISMAN    Male             Shooting               Violent
166                 Jackie ARKLÖV    Male             Shooting               Violent
167        Anthony Paul ARKWRIGHT    Male             Stabbing               Violent
168     Charles W. ARMENTROUT III    Male  Bludgeoning/Beating               Violent
169       Herbert Rowse ARMSTRONG    Male            Poisoning           Non-violent
170           John Eric ARMSTRONG    Male             Shooting               Violent
171            Lancelot ARMSTRONG    Male             Shooting               Violent
172            Pleasant ARMSTRONG    Male             Shooting               Violent
173          Ralph Dale ARMSTRONG    Male             Shooting               Violent
174         Shad Daniel ARMSTRONG    Male             Shooting               Violent
175       Shaun Anthony ARMSTRONG    Male             Shooting               Violent
176         Jermarr Carlos ARNOLD    Male             Shooting               Violent
177                John D. ARNOLD    Male             Stabbing               Violent
178                     Levi ARON    Male             Shooting               Violent
179            R andy ARROYO BAEZ    Male             Shooting               Violent
180                  Rahan ARSHAD    Male             Stabbing               Violent
181              M ark Sam ARTHUR    Male             Shooting               Violent
182                  Tommy ARTHUR    Male             Shooting               Violent
183         Dante Wyndham ARTHURS    Male        Strangulation               Violent
184              Kevin Lloyd ARTZ    Male  Bludgeoning/Beating               Violent
185                 Shoko ASAHARA    Male            Poisoning           Non-violent
186                Kojiro ASAKURA    Male  Bludgeoning/Beating               Violent
187               Mark James ASAY    Male             Shooting               Violent
188           Larry Gene ASHBROOK    Male             Shooting               Violent
189           Lazale Delane ASHBY    Male             Shooting               Violent
190              Troy Adam ASHMUS    Male             Shooting               Violent
191          Herman Dale ASHWORTH    Male  Bludgeoning/Beating               Violent
192               Valery ASRATYAN    Male            Poisoning           Non-violent
193            Andrew Simon ASTON    Male             Shooting               Violent
194               Samuel ATHERLEY    Male  Bludgeoning/Beating               Violent
195          Benjamin Tony ATKINS    Male             Shooting               Violent
196           Daryl Renard ATKINS    Male             Shooting               Violent
197     Frederick Benjamin ATKINS    Male             Stabbing               Violent
198          Joseph Ernest ATKINS    Male             Shooting               Violent
199     Philliph Alexander ATKINS    Male             Shooting               Violent
200           David Edward ATTIAS    Male             Shooting               Violent
201           Jeffrey Lee ATWATER    Male             Stabbing               Violent
202           Frank Jarvis ATWOOD    Male             Stabbing               Violent
203         Robert Ronald ATWORTH    Male             Shooting               Violent
204                J ohn AUSONIUS    Male             Shooting               Violent
205                 Ernest AUSTIN    Male        Strangulation               Violent
206            Perry Allen AUSTIN    Male             Stabbing               Violent
207             James David AUTRY    Male             Shooting               Violent
208            Pekka-Eric AUVINEN    Male             Shooting               Violent
209              Jorjik AVANESIAN    Male             Stabbing               Violent
210            Rufus Lee AVERHART    Male             Shooting               Violent
211                  Steven AVERY    Male             Stabbing               Violent
212               Alejandro AVILA    Male             Stabbing               Violent
213          Gabriel Adrian AVILA    Male             Shooting               Violent
214           Rigoberto AVILA Jr.    Male             Shooting               Violent
215      Dr. Arnold Asher AXILROD    Male             Stabbing               Violent
216           Erik Salvador AYALA    Male             Shooting               Violent
217        C arlos Manuel AYESTAS    Male        Strangulation               Violent
218                 Anthony AYRES    Male             Shooting               Violent
219                 Johnson AZIGA    Male             Shooting               Violent
220                      Sada ABE  Female            Poisoning           Non-violent
221          Kristi Anne ABRAHAMS  Female             Stabbing               Violent
222           Nicole M. ABUSHARIF  Female             Shooting               Violent
223           Brittny Marie ADAMS  Female             Shooting               Violent
224            Christine ADEWUNMI  Female             Shooting               Violent
225                 Kemi ADEYOOLA  Female            Poisoning           Non-violent
226                   Lydia ADLER  Female  Bludgeoning/Beating               Violent
227          Guen Garlejo AGUILAR  Female            Poisoning           Non-violent
228            Sara María ALDRETE  Female             Shooting               Violent
229         Nasra Yussef Al-ENEZI  Female             Stabbing               Violent
230        Maria del Rosio ALFARO  Female             Shooting               Violent
231                  Melanie ALIX  Female         Burning/Fire               Violent
232      Patricia Taylor ALLANSON  Female            Poisoning           Non-violent
233                  Eryn ALLEGRA  Female        Strangulation               Violent

In [ ]:
#Since I do have alot more men than women in my sample this shows that there are more male serial killers than women however both gender more likely to conduct violent crimes than non-violent

In [ ]:
# I do want to add more variables such as number of victims. Also, While doing this research according to the FBI to be considered a serial killer you have to have at least 2 victims. Some of the people on this list only have one. So, I want to create another new variables for if they are a serial killer or not and then group those results!

In [ ]:
#Regression - I want to run a regression to see if gender determines method types and if these methods are considered non-violent or violent. I will also want to control for number of victims once I add that to my dataset! I might also want to include countries as well.

In [24]:
import os
print(os.getcwd())

/Users/lailaa/Documents/GitHub/assignment-1-lailaaholmes